<a href="https://colab.research.google.com/github/patelmrunal/machine-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

6

In [ ]:
#Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[1, 7, 2],
                      [5, 10, 5]])
MATRIX

tensor([[ 1,  7,  2],
        [ 5, 10,  5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 5, 10,  5])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[2, 5, 7, 2],
                        [7, 3, 1, 2],
                        [3, 5, 4, 4],
                        [2, 5, 3, 5]]])
TENSOR

tensor([[[2, 5, 7, 2],
         [7, 3, 1, 2],
         [3, 5, 4, 4],
         [2, 5, 3, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 4])

### Random Tensors

In [ ]:
# Creating a random tensors
random_tesnsor = torch.rand(4,3,3)
random_tesnsor

tensor([[[0.8091, 0.7682, 0.9599],
         [0.8472, 0.2327, 0.0561],
         [0.6852, 0.3440, 0.5805]],

        [[0.0771, 0.3131, 0.3608],
         [0.9101, 0.2111, 0.4630],
         [0.8982, 0.9112, 0.2693]],

        [[0.8821, 0.0965, 0.2702],
         [0.8077, 0.2393, 0.9095],
         [0.0122, 0.0651, 0.9250]],

        [[0.6202, 0.0573, 0.7636],
         [0.4641, 0.3681, 0.2102],
         [0.5126, 0.1681, 0.3697]]])

In [ ]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #Color channel (R, G, B), Height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of ones
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [ ]:
float_32_tensor = torch.tensor([1.0, 4.0, 5.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 4., 5.], dtype=torch.float16)

In [ ]:
multi = float_16_tensor * float_32_tensor
multi

tensor([ 1., 16., 25.])

In [ ]:
multi.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([2,4,6], dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 2., 16., 30.])

### Geting Information from tensors

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0485, 0.5991, 0.8650, 0.0633],
        [0.7361, 0.7613, 0.6041, 0.0590],
        [0.7121, 0.1565, 0.3807, 0.3177]])

In [ ]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.0485, 0.5991, 0.8650, 0.0633],
        [0.7361, 0.7613, 0.6041, 0.0590],
        [0.7121, 0.1565, 0.3807, 0.3177]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

* Element-wise multiplication
* Matrix multiplication (Dot Product)

In [ ]:
# Element-wise multiplication

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
torch.matmul(torch.rand(2, 3) , torch.rand(3, 2))

tensor([[0.6236, 0.5931],
        [0.3913, 0.4670]])

### One of the most common errors in deep learning: shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape we can manupilate the shape of one of our tensor using a transpose

A transpose switches the axes and dimension of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
tensor_C = torch.tensor([[41,25,32],
                         [32,26,74],
                         [12,5,49],
                         [12,96,38]])

tensor_D = torch.tensor([[42,32,42],
                         [65,84,31],
                         [29,43,20],
                         [12,85,36]])

tensor_C.shape, tensor_D.shape

(torch.Size([4, 3]), torch.Size([4, 3]))

In [ ]:
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [ ]:
tensor_C.T, tensor_C.T.shape

(tensor([[41, 32, 12, 12],
         [25, 26,  5, 96],
         [32, 74, 49, 38]]),
 torch.Size([3, 4]))

In [ ]:
output = torch.mm(tensor_C.T , tensor_D)
print(output)
output.shape

tensor([[ 4294,  5536,  3386],
        [ 4037, 11359,  5412],
        [ 8031, 12577,  5986]])


torch.Size([3, 3])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the minimum value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the maximum value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
# Chnage the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [ ]:
# if we change z is equals to changes x (because in tensor both share same mnemory as input)
z[:,0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [ ]:
# satck tensor on top of each other
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12]])

In [ ]:
torch.hstack([torch.rand([4,3]),torch.rand([4,3])])

tensor([[0.1546, 0.8337, 0.8635, 0.1616, 0.0078, 0.1573],
        [0.2311, 0.6076, 0.1302, 0.6562, 0.3029, 0.9505],
        [0.7548, 0.4236, 0.2013, 0.0029, 0.1458, 0.6710],
        [0.5703, 0.9316, 0.9366, 0.4527, 0.3538, 0.6976]])

In [ ]:
torch.vstack([torch.rand([3,3]),torch.rand([3,3])])

tensor([[0.0776, 0.0155, 0.5143],
        [0.0774, 0.1477, 0.3238],
        [0.1505, 0.7635, 0.3400],
        [0.2662, 0.3178, 0.4893],
        [0.7601, 0.7264, 0.6793],
        [0.1132, 0.5220, 0.0944]])

In [ ]:
# squeeze and unsqueeze methods
x = torch.zeros(2,1,2,3,1,2)
x.size()

torch.Size([2, 1, 2, 3, 1, 2])

In [ ]:
# Squeeze method - remove all single dimwnsion from target tensor
y = torch.squeeze(x)
y.size ()

torch.Size([2, 2, 3, 2])

In [ ]:
y = torch.squeeze(x, (1))
y.size()

torch.Size([2, 2, 3, 1, 2])

In [ ]:
# Unsqueeze method - Returns a new tensor with a dimension of size one inserted at the specified position.
y = torch.unsqueeze(x, dim=0)
y.size()

torch.Size([1, 2, 1, 2, 3, 1, 2])

In [ ]:
y = torch.unsqueeze(x, dim=1)
y.size()

torch.Size([2, 1, 1, 2, 3, 1, 2])

In [ ]:
# permute - Returns a view of the original tensor input with its dimensions permuted
x = torch.randn(3,1,2,2,3,1)
x.size()

torch.Size([3, 1, 2, 2, 3, 1])

In [ ]:
y = torch.permute(x,(2,1,0,4,3,5))
y.size()

torch.Size([2, 1, 3, 3, 2, 1])

In [ ]:
x[0,0,0] = (45238)
x[0,0,0], y[0,0,0]

(tensor([[[45238.],
          [45238.],
          [45238.]],
 
         [[45238.],
          [45238.],
          [45238.]]]),
 tensor([[[45238.],
          [45238.]],
 
         [[45238.],
          [45238.]],
 
         [[45238.],
          [45238.]]]))

### indexing (Selecting data from tensors)

In [ ]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x [0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can select ":" for all of a traget diemnsion
x[:, 1]

tensor([[4, 5, 6]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
print(x[:,2,2])
print(x[:, :,2])

tensor([9])
tensor([[3, 6, 9]])


### PyTorch tensors and Numpy

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))