<a href="https://colab.research.google.com/github/patelmrunal/machine-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

6

In [5]:
#Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[1, 7, 2],
                      [5, 10, 5]])
MATRIX

tensor([[ 1,  7,  2],
        [ 5, 10,  5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 5, 10,  5])

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[2, 5, 7, 2],
                        [7, 3, 1, 2],
                        [3, 5, 4, 4],
                        [2, 5, 3, 5]]])
TENSOR

tensor([[[2, 5, 7, 2],
         [7, 3, 1, 2],
         [3, 5, 4, 4],
         [2, 5, 3, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 4])

### Random Tensors

In [15]:
# Creating a random tensors
random_tesnsor = torch.rand(4,3,3)
random_tesnsor

tensor([[[0.2317, 0.1415, 0.4539],
         [0.2998, 0.7160, 0.7617],
         [0.6869, 0.6385, 0.8624]],

        [[0.8976, 0.9585, 0.3669],
         [0.7401, 0.7446, 0.5317],
         [0.8556, 0.6453, 0.2779]],

        [[0.7129, 0.6917, 0.0272],
         [0.9547, 0.3568, 0.2926],
         [0.1851, 0.3652, 0.9679]],

        [[0.5735, 0.2285, 0.1026],
         [0.1172, 0.6408, 0.7422],
         [0.3928, 0.3692, 0.5702]]])

In [16]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #Color channel (R, G, B), Height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of ones
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
ones.dtype

torch.float32

In [20]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [23]:
float_32_tensor = torch.tensor([1.0, 4.0, 5.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1., 4., 5.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 4., 5.], dtype=torch.float16)

In [26]:
multi = float_16_tensor * float_32_tensor
multi

tensor([ 1., 16., 25.])

In [27]:
multi.dtype

torch.float32

In [28]:
int_32_tensor = torch.tensor([2,4,6], dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 2., 16., 30.])

### Geting Information from tensors

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7974, 0.3646, 0.7083, 0.5911],
        [0.5074, 0.5155, 0.6254, 0.2538],
        [0.3211, 0.9379, 0.4705, 0.7320]])

In [31]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.7974, 0.3646, 0.7083, 0.5911],
        [0.5074, 0.5155, 0.6254, 0.2538],
        [0.3211, 0.9379, 0.4705, 0.7320]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

* Element-wise multiplication
* Matrix multiplication (Dot Product)

In [37]:
# Element-wise multiplication

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [39]:
torch.matmul(torch.rand(2, 3) , torch.rand(3, 2))

tensor([[0.4278, 0.5470],
        [1.0741, 1.1894]])

### One of the most common errors in deep learning: shape errors

In [40]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape we can manupilate the shape of one of our tensor using a transpose

A transpose switches the axes and dimension of a given tensor

In [42]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [43]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [44]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [45]:
tensor_C = torch.tensor([[41,25,32],
                         [32,26,74],
                         [12,5,49],
                         [12,96,38]])

tensor_D = torch.tensor([[42,32,42],
                         [65,84,31],
                         [29,43,20],
                         [12,85,36]])

tensor_C.shape, tensor_D.shape

(torch.Size([4, 3]), torch.Size([4, 3]))

In [46]:
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [58]:
tensor_C.T, tensor_C.T.shape

(tensor([[41, 32, 12, 12],
         [25, 26,  5, 96],
         [32, 74, 49, 38]]),
 torch.Size([3, 4]))

In [59]:
output = torch.mm(tensor_C.T , tensor_D)
print(output)
output.shape

tensor([[ 4294,  5536,  3386],
        [ 4037, 11359,  5412],
        [ 8031, 12577,  5986]])


torch.Size([3, 3])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [60]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Finding the minimum value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Finding the maximum value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [63]:
# Finding the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [64]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [65]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

In [69]:
#Create a tensor
import torch
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [70]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [71]:
# Chnage the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [72]:
# if we change z is equals to changes x (because in tensor both share same mnemory as input)
z[:,0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [73]:
# satck tensor on top of each other
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12]])

In [74]:
torch.hstack([torch.rand([4,3]),torch.rand([4,3])])

tensor([[0.4216, 0.2373, 0.8111, 0.6248, 0.7822, 0.4098],
        [0.5340, 0.6834, 0.6528, 0.3471, 0.2834, 0.7521],
        [0.6123, 0.9834, 0.1826, 0.3628, 0.6243, 0.8568],
        [0.1239, 0.4262, 0.9717, 0.7912, 0.3054, 0.0376]])

In [75]:
torch.vstack([torch.rand([3,3]),torch.rand([3,3])])

tensor([[0.7759, 0.3159, 0.1600],
        [0.5838, 0.4831, 0.1120],
        [0.7900, 0.1813, 0.1004],
        [0.1655, 0.5094, 0.5793],
        [0.1461, 0.6626, 0.3235],
        [0.3402, 0.6316, 0.6537]])

In [76]:
# squeeze and unsqueeze methods
x = torch.zeros(2,1,2,3,1,2)
x.size()

torch.Size([2, 1, 2, 3, 1, 2])

In [77]:
# Squeeze method - remove all single dimwnsion from target tensor
y = torch.squeeze(x)
y.size ()

torch.Size([2, 2, 3, 2])

In [78]:
y = torch.squeeze(x, (1))
y.size()

torch.Size([2, 2, 3, 1, 2])

In [79]:
# Unsqueeze method - Returns a new tensor with a dimension of size one inserted at the specified position.
y = torch.unsqueeze(x, dim=0)
y.size()

torch.Size([1, 2, 1, 2, 3, 1, 2])

In [80]:
y = torch.unsqueeze(x, dim=1)
y.size()

torch.Size([2, 1, 1, 2, 3, 1, 2])

In [81]:
# permute - Returns a view of the original tensor input with its dimensions permuted
x = torch.randn(3,1,2,2,3,1)
x.size()

torch.Size([3, 1, 2, 2, 3, 1])

In [82]:
y = torch.permute(x,(2,1,0,4,3,5))
y.size()

torch.Size([2, 1, 3, 3, 2, 1])

In [83]:
x[0,0,0] = (45238)
x[0,0,0], y[0,0,0]

(tensor([[[45238.],
          [45238.],
          [45238.]],
 
         [[45238.],
          [45238.],
          [45238.]]]),
 tensor([[[45238.],
          [45238.]],
 
         [[45238.],
          [45238.]],
 
         [[45238.],
          [45238.]]]))

### indexing (Selecting data from tensors)

In [84]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# Let's index on our new tensor
x [0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
x[0][0]

tensor([1, 2, 3])

In [87]:
x[0][2][2]

tensor(9)

In [88]:
# You can select ":" for all of a traget diemnsion
x[:, 1]

tensor([[4, 5, 6]])

In [89]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [90]:
x[:,1,1]

tensor([5])

In [91]:
x[:,0]

tensor([[1, 2, 3]])

In [92]:
print(x[:,2,2])
print(x[:, :,2])

tensor([9])
tensor([[3, 6, 9]])


### PyTorch tensors and Numpy

In [93]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [94]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (Trying to take random out of random)

In [97]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5811, 0.3412, 0.2945, 0.3636],
        [0.3370, 0.1347, 0.9134, 0.2588],
        [0.7716, 0.4666, 0.0070, 0.5136]])
tensor([[0.4281, 0.8688, 0.6318, 0.5512],
        [0.0155, 0.7184, 0.5830, 0.9972],
        [0.2684, 0.9493, 0.3472, 0.2833]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [98]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 45
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tesnsors and PyTorch objects on the GPUs

* Use google colab for free GPU
* Use your own GPU
* Use cloud computing - GCP, AWS, etc..

In [99]:
!nvidia-smi

Wed Mar 18 02:02:30 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8             13W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [100]:
import torch
torch.cuda.is_available()

True

In [101]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [102]:
torch.cuda.device_count()

1

In [103]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [104]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [107]:
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])