<a href="https://colab.research.google.com/github/patelmrunal/machine-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

6

In [5]:
#Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[1, 7, 2],
                      [5, 10, 5]])
MATRIX

tensor([[ 1,  7,  2],
        [ 5, 10,  5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 5, 10,  5])

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[2, 5, 7, 2],
                        [7, 3, 1, 2],
                        [3, 5, 4, 4],
                        [2, 5, 3, 5]]])
TENSOR

tensor([[[2, 5, 7, 2],
         [7, 3, 1, 2],
         [3, 5, 4, 4],
         [2, 5, 3, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 4])

### Random Tensors

In [15]:
# Creating a random tensors
random_tesnsor = torch.rand(4,3,3)
random_tesnsor

tensor([[[0.9127, 0.0904, 0.5059],
         [0.8467, 0.5814, 0.2869],
         [0.1404, 0.3737, 0.9636]],

        [[0.5456, 0.0750, 0.4649],
         [0.9661, 0.2495, 0.9095],
         [0.9290, 0.4606, 0.7658]],

        [[0.6029, 0.2905, 0.9406],
         [0.4563, 0.0648, 0.8749],
         [0.3849, 0.9624, 0.5884]],

        [[0.5913, 0.3462, 0.3173],
         [0.5239, 0.8798, 0.9732],
         [0.8513, 0.9407, 0.3190]]])

In [16]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #Color channel (R, G, B), Height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of ones
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
ones.dtype

torch.float32

In [20]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [23]:
float_32_tensor = torch.tensor([1.0, 4.0, 5.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1., 4., 5.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 4., 5.], dtype=torch.float16)

In [26]:
multi = float_16_tensor * float_32_tensor
multi

tensor([ 1., 16., 25.])

In [27]:
multi.dtype

torch.float32

In [28]:
int_32_tensor = torch.tensor([2,4,6], dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 2., 16., 30.])

### Geting Information from tensors

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9874, 0.7867, 0.7179, 0.9567],
        [0.5947, 0.0425, 0.7833, 0.2865],
        [0.7398, 0.5720, 0.7950, 0.4195]])

In [31]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.9874, 0.7867, 0.7179, 0.9567],
        [0.5947, 0.0425, 0.7833, 0.2865],
        [0.7398, 0.5720, 0.7950, 0.4195]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

* Element-wise multiplication
* Matrix multiplication (Dot Product)

In [37]:
# Element-wise multiplication

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [43]:
torch.matmul(torch.rand(2, 3) , torch.rand(3, 2))

tensor([[1.5140, 0.6895],
        [1.0040, 0.3055]])

### One of the most common errors in deep learning: shape errors

In [45]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape we can manupilate the shape of one of our tensor using a transpose

A transpose switches the axes and dimension of a given tensor

In [48]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [51]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [52]:
tensor_C = torch.tensor([[41,25,32],
                         [32,26,74],
                         [12,5,49],
                         [12,96,38]])

tensor_D = torch.tensor([[42,32,42],
                         [65,84,31],
                         [29,43,20],
                         [12,85,36]])

tensor_C.shape, tensor_D.shape

(torch.Size([4, 3]), torch.Size([4, 3]))

In [53]:
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [54]:
tensor_C.T, tensor_C.T.shape

(tensor([[41, 32, 12, 12],
         [25, 26,  5, 96],
         [32, 74, 49, 38]]),
 torch.Size([3, 4]))

In [56]:
output = torch.mm(tensor_C.T , tensor_D)
print(output)
output.shape

tensor([[ 4294,  5536,  3386],
        [ 4037, 11359,  5412],
        [ 8031, 12577,  5986]])


torch.Size([3, 3])