<a href="https://colab.research.google.com/github/patelmrunal/machine-learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

6

In [5]:
#Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[1, 7, 2],
                      [5, 10, 5]])
MATRIX

tensor([[ 1,  7,  2],
        [ 5, 10,  5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 5, 10,  5])

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[2, 5, 7, 2],
                        [7, 3, 1, 2],
                        [3, 5, 4, 4],
                        [2, 5, 3, 5]]])
TENSOR

tensor([[[2, 5, 7, 2],
         [7, 3, 1, 2],
         [3, 5, 4, 4],
         [2, 5, 3, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 4])

### Random Tensors

In [15]:
# Creating a random tensors
random_tesnsor = torch.rand(4,3,3)
random_tesnsor

tensor([[[0.9365, 0.8324, 0.1701],
         [0.2931, 0.0227, 0.7529],
         [0.4754, 0.8302, 0.3259]],

        [[0.2104, 0.5464, 0.5070],
         [0.9152, 0.6685, 0.4091],
         [0.2539, 0.8692, 0.2545]],

        [[0.6215, 0.3551, 0.4950],
         [0.5461, 0.4267, 0.2040],
         [0.1457, 0.4985, 0.5964]],

        [[0.8933, 0.6690, 0.0144],
         [0.5220, 0.2930, 0.5176],
         [0.5153, 0.1788, 0.9233]]])

In [16]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #Color channel (R, G, B), Height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of ones
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
ones.dtype

torch.float32

In [20]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [23]:
float_32_tensor = torch.tensor([1.0, 4.0, 5.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1., 4., 5.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 4., 5.], dtype=torch.float16)

In [26]:
multi = float_16_tensor * float_32_tensor
multi

tensor([ 1., 16., 25.])

In [27]:
multi.dtype

torch.float32

In [28]:
int_32_tensor = torch.tensor([2,4,6], dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 2., 16., 30.])

### Geting Information from tensors

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5406, 0.0019, 0.9221, 0.0740],
        [0.6669, 0.9211, 0.1281, 0.3797],
        [0.7424, 0.9766, 0.5395, 0.1636]])

In [31]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.5406, 0.0019, 0.9221, 0.0740],
        [0.6669, 0.9211, 0.1281, 0.3797],
        [0.7424, 0.9766, 0.5395, 0.1636]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Manipulating tensors (tensor operations)

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

* Element-wise multiplication
* Matrix multiplication (Dot Product)

In [37]:
# Element-wise multiplication

print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [39]:
torch.matmul(torch.rand(2, 3) , torch.rand(3, 2))

tensor([[1.0210, 1.1730],
        [0.3603, 0.4030]])

### One of the most common errors in deep learning: shape errors

In [40]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape we can manupilate the shape of one of our tensor using a transpose

A transpose switches the axes and dimension of a given tensor

In [41]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [43]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [44]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [45]:
tensor_C = torch.tensor([[41,25,32],
                         [32,26,74],
                         [12,5,49],
                         [12,96,38]])

tensor_D = torch.tensor([[42,32,42],
                         [65,84,31],
                         [29,43,20],
                         [12,85,36]])

tensor_C.shape, tensor_D.shape

(torch.Size([4, 3]), torch.Size([4, 3]))

In [46]:
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [47]:
tensor_C.T, tensor_C.T.shape

(tensor([[41, 32, 12, 12],
         [25, 26,  5, 96],
         [32, 74, 49, 38]]),
 torch.Size([3, 4]))

In [48]:
output = torch.mm(tensor_C.T , tensor_D)
print(output)
output.shape

tensor([[ 4294,  5536,  3386],
        [ 4037, 11359,  5412],
        [ 8031, 12577,  5986]])


torch.Size([3, 3])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [52]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# Finding the minimum value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
# Finding the maximum value
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# Finding the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [59]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [60]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
x.argmin()

tensor(0)

In [62]:
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing

In [81]:
#Create a tensor
import torch
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [82]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
# Chnage the view