In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


### Creating Tensors

In [5]:
# scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as python int
scalar.item()

6

In [11]:
#Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [12]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [20]:
#Matrix
MATRIX = torch.tensor([[1, 7],
                      [5, 10]])
MATRIX

tensor([[ 1,  7],
        [ 5, 10]])

In [21]:
MATRIX.ndim

2

In [22]:
MATRIX[1]

tensor([ 5, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
#TENSOR
TENSOR = torch.tensor([[[2, 5, 7, 2],
                        [7, 3, 1, 2],
                        [3, 5, 4, 4],
                        [2, 5, 3, 5]]])
TENSOR

tensor([[[2, 5, 7, 2],
         [7, 3, 1, 2],
         [3, 5, 4, 4],
         [2, 5, 3, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 4, 4])